"""new_tabl

Revision ID: 14057e32129f
Revises: 38aaf09c56da
Create Date: 2023-05-17 22:13:42.220180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14057e32129f'
down_revision = '38aaf09c56da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.alter_column('tag_to_image', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tag_to_image', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tag_to_image', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tag_to_image', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('blacklisted_tokens')
    # ### end Alembic commands ###
