"""upd

Revision ID: 38aaf09c56da
Revises: eabd5cef78d7
Create Date: 2023-05-16 12:52:25.829980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38aaf09c56da'
down_revision = 'eabd5cef78d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_to_image')


    op.create_table('tag_to_image',
                sa.Column('tag_id', sa.Integer(), nullable=False),
                sa.Column('image_id', sa.Integer(), nullable=False),
                sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
                sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
                sa.PrimaryKeyConstraint('tag_id', 'image_id')
                    )

#    op.add_column('tag_to_image', sa.Column('id', sa.Integer(), nullable=False))
#    op.alter_column('tag_to_image', 'tag_id',
#               existing_type=sa.INTEGER(),
#               nullable=True)
#    op.alter_column('tag_to_image', 'image_id',
#               existing_type=sa.INTEGER(),
#               nullable=True)
#    op.drop_constraint('tag_to_image_image_id_fkey', 'tag_to_image', type_='foreignkey')
#    op.drop_constraint('tag_to_image_tag_id_fkey', 'tag_to_image', type_='foreignkey')
#    op.create_foreign_key(None, 'tag_to_image', 'images', ['image_id'], ['id'], ondelete='CASCADE')
#    op.create_foreign_key(None, 'tag_to_image', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_to_image', type_='foreignkey')
    op.drop_constraint(None, 'tag_to_image', type_='foreignkey')
    op.create_foreign_key('tag_to_image_tag_id_fkey', 'tag_to_image', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('tag_to_image_image_id_fkey', 'tag_to_image', 'images', ['image_id'], ['id'])
    op.alter_column('tag_to_image', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tag_to_image', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tag_to_image', 'id')
    # ### end Alembic commands ###
