"""users upgrade

Revision ID: eabd5cef78d7
Revises: ba6bf3572799
Create Date: 2023-05-13 15:27:53.669412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabd5cef78d7'
down_revision = 'ba6bf3572799'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    # ### end Alembic commands ###
